{% set name = "dandischema" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d9ca25839c2ea2cc27b0bf4908261aa9397df8c1c4b61acb6c0c9759b99bc4e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - email-validator >=1.0.3
    - jsonschema
    - pydantic >=1.8.1
    - ruamel.yaml
    - typing_extensions

test:
  requires:
    - pytest
    - pytest-cov
    - requests
  source_files:
    - tox.ini
  imports:
    - dandischema
  commands:
    - python -m pytest -vv --pyargs dandischema

about:
  home: https://github.com/dandi/dandischema
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Schemata for DANDI archive project
  description: |
    A Python library for maintaining and managing DANDI metadata schemata. The
    library helps create and validate DANDI schema-compliant metadata for
    Dandisets and assets.
  dev_url: https://github.com/dandi/dandischema

extra:
  recipe-maintainers:
    - yarikoptic
    - jwodder
