{% set name = "dandischema" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1b41c76d08cad6a87c427a3258b89299ab127d76b3ee9d31ae96da7343af4fe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - email-validator >=1.0.3
    - jsonschema
    - pydantic >=1.8.1
    - requests
    - rfc3987
    - typing_extensions

test:
  requires:
    - pytest
    - pytest-cov
  source_files:
    - tox.ini
  imports:
    - dandischema
  commands:
    - python -m pytest -vv --pyargs dandischema

about:
  home: https://github.com/dandi/dandischema
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Schemata for DANDI archive project
  description: |
    A Python library for maintaining and managing DANDI metadata schemata. The
    library helps create and validate DANDI schema-compliant metadata for
    Dandisets and assets.
  dev_url: https://github.com/dandi/dandischema

extra:
  recipe-maintainers:
    - yarikoptic
    - jwodder
