{% set name = "dandischema" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad8d6f358b3512e789afc9c528a3b9cc9c83de298c3552b03c5e681cb416e865

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioningit
  run:
    - python >={{ python_min }}
    - email-validator >=1.0.3
    - jsonschema
    - pydantic >=2.4,<3
    - requests
    - rfc3987
    - zarr-checksum

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-rerunfailures
    - python {{ python_min }}
  source_files:
    - tox.ini
  imports:
    - dandischema
  commands:
    - python -m pytest -vv --pyargs dandischema

about:
  home: https://github.com/dandi/dandischema
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Schemata for DANDI archive project
  description: |
    A Python library for maintaining and managing DANDI metadata schemata. The
    library helps create and validate DANDI schema-compliant metadata for
    Dandisets and assets.
  dev_url: https://github.com/dandi/dandischema

extra:
  recipe-maintainers:
    - yarikoptic
    - jwodder
