{% set name = "dandischema" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bef83ee03b9ee4c406a667771ca129541f1a27e9e1f0bed581eb1104ebc326aa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - versioningit
  run:
    - python >=3.8
    - email-validator >=1.0.3
    - jsonschema
    - pydantic >=2.4,<3
    - requests
    - rfc3987
    - zarr-checksum

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-rerunfailures
  source_files:
    - tox.ini
  imports:
    - dandischema
  commands:
    - python -m pytest -vv --pyargs dandischema

about:
  home: https://github.com/dandi/dandischema
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Schemata for DANDI archive project
  description: |
    A Python library for maintaining and managing DANDI metadata schemata. The
    library helps create and validate DANDI schema-compliant metadata for
    Dandisets and assets.
  dev_url: https://github.com/dandi/dandischema

extra:
  recipe-maintainers:
    - yarikoptic
    - jwodder
